#!/bin/sh
#
# $Id: reconf,v 1.1 1999-12-29 14:20:37 bagder Exp $
#
# re autoconf/automake shell script
#

die(){
	echo "$@" ; exit
}

aclocal    || die "ahhhhh"
autoheader || die "ahhhhh"
automake   || die "ahhhhh"
autoconf   || die "ahhhhh"

