#!/bin/sh
#
# $Id: reconf,v 1.2 2000-01-10 23:36:14 bagder Exp $
#
# re autoconf/automake shell script
#

die(){
	echo "$@" ; exit
}

aclocal    || die "ahhhhh"
autoheader || die "ahhhhh"
automake   || die "ahhhhh"
autoconf   || die "ahhhhh"

